apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: echo-server
        image: ghcr.io/nonicked/argocd-demo:latest
        env:
        - name: LOGS_LEVEL
          value: "debug"
